alsa_hw_mapping: plughw:1,0
mixer_control_name: Speaker    # look at amixer scontrols for available controls
format: cd # look at aplay --help for available formats
file_type: wav
channels: 1
hook_gpio: 22
hook_type: NC # or 'NO' depending on your hardware configuration
invert_hook: false  # Set to true if your hook behavior is reversed (recording starts when handset is down instead of up)
# Software bounce compensation this is the length of time (in seconds) that the component will ignore changes in state after an initial change.
hook_bounce_time: 0.1 # float or None
recording_limit: 300
sample_rate: 44100

# Record greeting message button (Set to 0 to skip setup of this feature)
record_greeting_gpio: 27
record_greeting_type: NC # or 'NO' depending on your hardware configuration
# Software bounce compensation this is the length of time (in seconds) that the component will ignore changes in state after an initial change.
record_greeting_bounce_time: 0.1 # float or None

# The beep sound is played when the user picks up the phone
beep: uploads/beep.wav
beep_volume: 0.7
beep_start_delay: 0.0
beep_include_in_message: false

# The greeting sound is played when the user picks up the phone
greeting: uploads/hello2.wav
greeting_volume: 1.0
greeting_start_delay: 1.5

# The time_exceeded sound is played when the user has been recording for too long
time_exceeded: uploads/beep.wav
time_exceeded_volume: 1.0

recordings_path: /home/admin/rotary-phone-audio-guestbook/recordings
time_exceeded_length: 300

shutdown_gpio: 0 #Set GPIO pin here --> Note: Pin is active LOW, pull Pin to GND to activate shutdown
shutdown_button_hold_time: 2 # default 2 seconds
